[tool.poetry]
name = "diagram"
version = "0.1.0"
description = ""
authors = ["Joel Freeman <joel@jxel.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
diagrams = "^0.23.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
