---
openapi: 3.0.0
info:
  version: 1.0.0
  title: URL Shortener API
  description: URL Shortener similar to bit.ly

servers:
  - url: "http://localhost:8080"
    description: Development server

paths:
  /api/v1/url:
    get:
      summary: Get all URLs
      description: Returns a list of URLs that have been created by all users.
      responses:
        '200':
          description: A list of URLs.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Url"
    post:
      summary: Create a URL
      description: Creates a new short URL object.
      requestBody:
        description: The URL to shorten.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUrlRequest"
      responses:
        '201':
          description: The created URL.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Url"
        '400':
          description: The request was invalid.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/v1/url/{id}:
    get:
      summary: Get a URL by ID
      description: Returns the URL with the specified ID.
      parameters:
        - name: id
          in: path
          description: The ID of the URL to get.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: The requested URL.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Url"
        '404':
          description: The URL with the specified ID was not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    put:
      summary: Update a URL by ID
      description: Updates the URL with the specified ID.
      parameters:
        - name: id
          in: path
          description: The ID of the URL to update.
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: The new URL data.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUrlRequest"
      responses:
        '200':
          description: The updated URL.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Url"
        '404':
          description: The URL with the specified ID was not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    delete:
      summary: Delete a URL by ID
      description: Deletes the URL with the specified ID.
      parameters:
        - name: id
          in: path
          description: The ID of the URL to delete.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: The URL was deleted successfully.
        '404':
          description: The URL with the specified ID was not found.
components:
  securitySchemas:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    Url:
      type: object
      properties:
        id:
          type: integer
          format: int64
        long_url:
          type: string
        short_url:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        user_id:
          type: integer
          format: int64
      required:
        - long_url
      example:
        id: 1
        long_url: "https://www.example.com"
        short_url: "abc123-generated-by-server"
        created_at: "2023-04-25T12:34:56Z"
        updated_at: "2023-04-25T12:34:56Z"
        user_id: 1

    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        urls:
          type: array
          items:
            $ref: '#/components/schemas/Url'
        is_admin:
          type: boolean
      required:
        - username
      example:
        id: 1
        username: "user123"
        urls:
          - id: 1
            long_url: "https://www.example.com"
            short_url: "abc123"
            created_at: "2023-04-25T12:34:56Z"
            updated_at: "2023-04-25T12:34:56Z"
            user_id: 1
        is_admin: false

    AuthenticationInput:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
      example:
        username: "user123"
        password: "password123"
